# Effect Pipes: map, tap, mapError, and tapError

In Effect pipes, you'll frequently encounter these four utility functions:

-  `map`: Transforms the success value of type `A` in `Effect<A, E, R>` to a new type `B`.
- `tap`: Performs a side effect on the success value without changing it.
- `mapError`: Transforms the error value of type `E` in `Effect<A, E, R>` to a new error type.
- `tapError`: Performs a side effect on the error value without changing it.
## map

The `map` function can use the previous value in the pipe to derive a new state:

```ts
const result = pipe(
  divide(1, 2),
  Effect.catchAll(() => Effect.succeed(null)),
  Effect.map((previousValue: number | null) => (previousValue ?? 0) - 5),
  Effect.runSync
);

result; // number
```

It can also completely replace the value:

```ts
const result = pipe(
  divide(1, 2),
  Effect.catchAll(() => Effect.succeed(null)),
  Effect.map(() => true),
  Effect.runSync
);

result; // boolean
```

Multiple `map` calls can be chained:

```ts
const result = pipe(
  Effect.succeed(5),
  Effect.map((previousValue) => previousValue - 5),
  Effect.map((previousValue) => previousValue * 80),
  Effect.map((previousValue) => previousValue + 10),
  Effect.map((previousValue) => String(previousValue)),
  Effect.runSync
);

result; // string
```

The signature of `map` is as follows:

```ts
export declare const map: {
  <A, B>(f: (a: A) => B): <E, R>(self: Effect<A, E, R>) => Effect<B, E, R>;
  <A, E, R, B>(self: Effect<A, E, R>, f: (a: A) => B): Effect<B, E, R>;
};
```

As we can see, `map` has two overloads:

1. The first takes a callback that transforms `A` (the success value of the previous Effect) and returns a function accepting `self`.
2. The second takes `self` as the first argument and the transforming function as the second argument.

In both cases, `map` transforms an `Effect<A, E, R>` into an `Effect<B, E, R>`, where `B` is the result type of the mapping function.

You can also do type narrowing:

```ts
pipe(
  divide(1, 2),
  Effect.map(() => 5 as const),
  (effect) => effect, // Effect<5, Error, never>
);
```

Here, `5` becomes the new value in the success channel with a narrowed type.

## tap

The `tap` function is useful for performing side effects without modifying the value in the pipe:

```ts
const result = pipe(
  divide(1, 2),
  Effect.catchAll(() => Effect.succeed(null)),
  Effect.tap((value) => {
    console.log(value);
  }),
  Effect.runSync
);
result; // number | null
```

In this example, the value is logged to the console, but the type of `result` remains `number | null`.

Even if you return a value from the `tap` callback, it won't affect the result:

```ts
const result = Effect.succeed(2).pipe(
  Effect.catchAll(() => Effect.succeed(null)),
  Effect.tap((value) => {
    console.log(value);
    return "a new value";
  }),
  Effect.runSync
);

result; // 2
```

## mapError

`mapError` is similar to `map`, but it's used to change the error type in the pipe:

```typescript
const result = divide(0, 2).pipe(
  Effect.mapError((_error) => new Error("Something went wrong")),
  Effect.runSync,
);
// Throws: Error - Something went wrong
```

Here, the original error is captured and transformed into a new error with a custom message.

## tapError

`tapError` is used to perform side effects on errors without modifying them:

```typescript
const result = divide(0, 2).pipe(
  Effect.tapError((error) => {
    console.error(error);
    return Effect.unit
  }),
  Effect.runSync
);
// Logs: Error: Can't divide by zero
// Throws: Error: Can't divide by zero
```

In this case, the error is logged to the console, but the error type in the pipe remains unchanged.

Note that `tapError` requires you to return an Effect. If you don't, you'll get a type error:

```ts
const result = Effect.succeed(2).pipe(
  // Type error: Argument of type '(error: never) => void' is not assignable to 
  // parameter of type '(e: never) => Effect<unknown, unknown, unknown>'
  Effect.tapError((error) => {
    console.error(error);
  }),
  Effect.runSync
);
```

To fix this, return an Effect:

```ts
const result = Effect.succeed(2).pipe(
  Effect.tapError((error) => {
    console.error(error);
    return Effect.void;
  }),
  Effect.runSync
);
```

`Effect.void` is an Effect that succeeds with void:

```ts
const _void: Effect<void> = core.void;

/** @internal */ 
const void_: Effect.Effect<void> = succeed(void 0);
```